apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: test1234        
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        awsElasticBlockStore:
          volumeID: "vol-05f7d979ea3663562"
          fsType: ext4  
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
  labels:
    app: wordpress
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql
  type: LoadBalancer
