apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-sample-linux-app
  name: eks-sample-linux-deployment-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      volumes:
      - name: log-volume
        hostPath:
          path: /var/log/nginx
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
      - name: log-updater
        image: alpine
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx-host
        command: ["/bin/sh"]
        args: ["-c", "while true; do cp -u /var/log/nginx/*.log /var/log/nginx-host && sleep 120; done"]

      containers:
      - image: public.ecr.aws/nginx/nginx:1.21
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 64Mi
            memory: 250m
          requests:
            cpu: 64Mi
            memory: 250m
      nodeSelector:
        kubernetes.io/os: linux
