apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-sample-linux-app
  name: eks-sample-linux-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - image: public.ecr.aws/nginx/nginx:1.21
        imagePullPolicy: IfNotPresent
        name: nginx
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/log/1/nginx.log 2>&1; sleep 1; done"]
        volumeMounts:
        - name: logs-volume
          mountPath: /var/log/1
    volumes:
    - name: logs-volume
      hostPath:
        path: /var/log/1
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 64Mi
            memory: 250m
          requests:
            cpu: 64Mi
            memory: 250m
      nodeSelector:
        kubernetes.io/os: linux
